### ISSUE TITLE
Uniquely identifying street segment for street quality aggregation

### ISSUE THREAD

**Issue by patwater** [argo-marketplace/SmartContracts-for-StreetMaintenance#3]
Getting this right is important so we build this awesome smart contracts future upon a solid technical foundation. 

The preferred technical path here would be to leverage the Shared Streets spec so we can ride the wave of that emergent global standard. 

@vr00n @ishacusp @gauravcusp please dig into the [Shared Streets spec](https://github.com/sharedstreets/sharedstreets-ref-system) and report here on how that can sync up. 

See here for the current SQUID schema that's currently utilized as part of the core SQUID pipeline. The centerline_id is what we want to be sure syncs up with the Shared_Streets spec 👍 

id SERIAL PRIMARY KEY,
                   timestamp Text,
                   v_value numeric(10,5),
                   geometry Geometry,
                   image_url Text,
                   image_lab Text,
                   trip_id Text,
                   centerline_id Text,
                   original_x Text,
                   original_y Text,
                   snapped_x Text,
                   snapped_y Text,
                   defect_score numeric(10,5),
                   lane_marking_score numeric(10,5),
                   color_score numeric(10,5),
                   cv_score numeric(10,5),
                   muni_name Text

Note that's about to be updated so stay tuned and looking to stay nice and synced up in this important foundation laying phase. One key update for this purpose is @dmarulli 's preferred path is to have the Shared Streets Spec unique street identifier as the table primary key.

1T1D and CC @grahamulator @dmarulli

**Comment by vr00n** [comment]
Not in scope for the short term until we finish a working prototype with Ty and SOUQ based on our conversation last weekend.

We will absolutely revisit this after completing a working engagement with SOUQ.
